@startuml
package deliverable.package {
  abstract class Deliverable {
    weight : float
  }

  class Tutorial
  class Quiz {
    time_opened : string,
    time_closed : string,
    allotted_time : string,
    type : string
  }

  class Assignment {
    due_date : datetime,
    submission_type : string,
    grade : float
  }

  class BackgroundSurvey

  class Tutorial implements Deliverable
  class Quiz implements Deliverable
  class Assignment implements Deliverable
  class BackgroundSurvey implements Deliverable
}

class DeliverableFactory {
  create_deliverable (deliverable_type)
}

DeliverableFactory ..> Deliverable

@enduml
