@startuml
participant VisitableInterface
participant Submission
participant GradesVisitor
participant CommentsVisitor
participant Student

== Updating Submission ==
VisitableInterface->Submission:accept(AbstractVisitor: GradesVisitor)
Submission->GradesVisitor:visit(Visitable: Submission)
GradesVisitor->Submission:update_grade(grade: integer)
Submission->CommentsVisitor:visit(Visitable: Submission)
CommentsVisitor->Submission:update_comment(comment: string)

== Updating Student ==
VisitableInterface->Student:accept(AbstractVisitor: GradesVisitor)
Student->GradesVisitor:visit(Visitable: Student)
GradesVisitor->Student:update_grade(grade: integer)
Student->CommentsVisitor:visit(Visitable: Student)
CommentsVisitor->Student:update_comment(comment: string)
@enduml

