@startuml
participant VisitableInterface
participant Submission
participant GradesVisitor
participant CommentsVisitor
participant Student
participant FinalGradesVisitor

== Updating Submission ==
VisitableInterface->Submission:accept(AbstractVisitor: GradesVisitor)
Submission->GradesVisitor:visit(Visitable: Submission)
GradesVisitor->Submission:update_grade()
Submission->CommentsVisitor:visit(Visitable: Submission)
CommentsVisitor->Submission:update_comment()

== Updating Final Grade ==
VisitableInterface->Student:accept(AbstractVisitor: GradesVisitor)
Student->GradesVisitor:visit(Visitable: Student)
FinalGradesVisitor->Student:update_grade()
@enduml

